#!/bin/bash

SOUND_CARD_PCI_ID=01:08.0
GPU_PCI_ID=02:00.0
USB1_PCI_ID=00:02.0
USB1_PCI_ID=00:02.1
USB2_PCI_ID=00:04.0
USB2_PCI_ID=00:04.1

setpci -v -s "*:*.*" latency_timer=c0
setpci -v -s $SOUND_CARD_PCI_ID latency_timer=ff
setpci -v -s $USB1_PCI_ID latency_timer=cf
setpci -v -s $USB1_PCI_ID latency_timer=cf
setpci -v -s $USB2_PCI_ID latency_timer=cf
setpci -v -s $USB2_PCI_ID latency_timer=cf
exit 0 
