#!/bin/bash

# Check CPU affinity of a process and it's threads

pname="$@" # for example

echo -e "-->Checking CPU affinity of process and it's threads<--\n"

tput setab 0

for pid in $(pgrep "${pname}") ; do 
    [ "${pid}" != "" ] || exit
    echo "PID: ${pid}"
    for tid in \
          $(ps --no-headers -ww -p "${pid}" -L -olwp | sed 's/$/ /' | tr  -d '\n') ; do
        taskset -cp "${tid}"  # substitute thread id in place of a process id
    done
done

echo -e "\n"

tput setab 0

exit
