#!/bin/sh

########################################################################
#
#  lpaBFQ - show BFQ tunables
#

# Functions

function func_freshHeadr(){

clear

sleep 0.2

tput setab 0
}

function func_pause(){
   read -p "$*"
}

# Start of (dislpayed) Script

tput setab 0

func_freshHeadr

echo -en "\e[1;37m"
echo -e "\e[1;30m-->\e[1;32m\e[1;93mChecking /proc/sys/vm\e[1;30m<--" 
echo -e "\e[1;34m <----------------------->\n"
echo -e "\e[1;30m--------------------------------------------------------------------------------"
echo -en "\e[1;36m  admin_reserve_kbytes                                  "
 
cat '/proc/sys/vm/admin_reserve_kbytes' 
 

echo -en "\e[1;36m  block_dump                                            "
 
cat '/proc/sys/vm/block_dump'
 

echo -en "\e[1;36m  dirty_background_bytes                                "
 
cat '/proc/sys/vm/dirty_background_bytes' 
 

echo -en "\e[1;36m  dirty_background_ratio                                "
 
cat '/proc/sys/vm/dirty_background_ratio' 
 

echo -en "\e[1;36m  dirty_bytes                                           "
 
cat '/proc/sys/vm/dirty_bytes' 
 

echo -en "\e[1;36m  dirty_expire_centisecs                                "
 
cat '/proc/sys/vm/dirty_expire_centisecs'
 

echo -en "\e[1;36m  dirty_ratio                                           "

 
cat '/proc/sys/vm/dirty_ratio' 
 

echo -en "\e[1;36m  dirty_writeback_centisecs                             "
 
cat '/proc/sys/vm/dirty_writeback_centisecs'  
 

echo -en "\e[1;36m  drop_caches                                           "
 
cat '/proc/sys/vm/drop_caches' 
 

echo -en "\e[1;36m  extfrag_threshold                                     "
 
cat '/proc/sys/vm/extfrag_threshold' 
 

echo -en "\e[1;36m  hugepages_treat_as_movable                            "
 
cat '/proc/sys/vm/hugepages_treat_as_movable' 
 

echo -en "\e[1;36m  hugetlb_shm_group                                     "
 
cat '/proc/sys/vm/hugetlb_shm_group' 
 

echo -en "\e[1;36m  lowmem_reserve_ratio                                  "
 
cat '/proc/sys/vm/lowmem_reserve_ratio' 
 

echo -en "\e[1;36m  max_map_count                                         "
 
cat '/proc/sys/vm/max_map_count' 
 

echo -en "\e[1;36m  memory_failure_early_kill                             "
 
cat '/proc/sys/vm/memory_failure_early_kill' 
 

echo -en "\e[1;36m  memory_failure_recovery                               "
 
cat '/proc/sys/vm/memory_failure_recovery'
 

echo -en "\e[1;36m  min_free_kbytes                                       "
 
cat '/proc/sys/vm/min_free_kbytes' 
 

echo -en "\e[1;36m  min_slab_ratio                                        "
 
cat '/proc/sys/vm/min_slab_ratio' 
 

echo -en "\e[1;36m  min_unmapped_ratio                                    "
 
cat '/proc/sys/vm/min_unmapped_ratio' 
 

echo -en "\e[1;36m  mmap_min_addr                                         "
 
cat '/proc/sys/vm/mmap_min_addr' 
 

echo -en "\e[1;36m  nr_hugepages                                          "
 
cat '/proc/sys/vm/nr_hugepages' 
 

echo -en "\e[1;36m  nr_hugepages_mempolicy                                "
 
cat '/proc/sys/vm/nr_hugepages_mempolicy' 
 

echo -en "\e[1;36m  nr_overcommit_hugepages                               "
 
cat '/proc/sys/vm/nr_overcommit_hugepages' 
 

echo -en "\e[1;36m  nr_pdflush_threads                                    "
 
 cat '/proc/sys/vm/nr_pdflush_threads' 
 

echo -en "\e[1;36m  numa_zonelist_order                                   "
 
cat '/proc/sys/vm/numa_zonelist_order' 
 

echo -en "\e[1;36m  oom_dump_tasks                                        "
 
cat '/proc/sys/vm/oom_dump_tasks' 
 

echo -en "\e[1;36m  oom_kill_allocating_task                              "
 
cat '/proc/sys/vm/oom_kill_allocating_task' 
 

echo -en "\e[1;36m  overcommit_memory                                     "
 
cat '/proc/sys/vm/overcommit_memory' 
 

echo -en "\e[1;36m  overcommit_ratio                                      "
 
cat '/proc/sys/vm/overcommit_ratio' 
 

echo -en "\e[1;36m  page-cluster                                          "
 
cat '/proc/sys/vm/page-cluster' 
 

echo -en "\e[1;36m  panic_on_oom                                          "
 
cat '/proc/sys/vm/panic_on_oom' 
 

echo -en "\e[1;36m  percpu_pagelist_fraction                              "
 
cat '/proc/sys/vm/percpu_pagelist_fraction'
 

echo -en "\e[1;36m  scan_unevictable_pages                                "
 
cat '/proc/sys/vm/scan_unevictable_pages' 
 

echo -en "\e[1;36m  stat_interval                                         "
 
cat '/proc/sys/vm/stat_interval' 
 

echo -en "\e[1;36m  swappiness                                            "
 
cat '/proc/sys/vm/swappiness' 
 

echo -en "\e[1;36m  user_reserve_kbytes                                   "
 
cat '/proc/sys/vm/user_reserve_kbytes'
 

echo -en "\e[1;36m  vfs_cache_pressure                                    "
 
cat '/proc/sys/vm/max_map_count' 
 

echo -en "\e[1;36m  zone_reclaim_mode                                     "

cat '/proc/sys/vm/zone_reclaim_mode' 
echo -e "\e[1;30m--------------------------------------------------------------------------------"
echo -e "\e[1;37m"
tput setab 0
exit 0
